version: "0.1"

services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/code
    working_dir: /code
    ports:
      - 3000:3000
    command: npm start

  backend:
    restart: always
    build: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/code
    working_dir: /code
    command: python Run.py

  postgres:
    image: postgres
    volumes:
       - postgres:/data/postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
