version: "0.1"

services:
  frontend:
    container_name: frontend_container
    build: frontend
    ports:
      - 3000:3000
    command: ["npm", "start"]

  backend:
    container_name: backend_container
    restart: always
    build: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/code
    working_dir: /code
    links:
      - postgres
    command: ["python", "Run.py"]

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    links:
      - postgres
    restart: unless-stopped
