version: "2"
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/code
    working_dir: /code
    ports:
      - 3000:3000
    command: npm start

  backend:
    restart: always
    build: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/code
    working_dir: /code
    command: python Run.py

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 5050:80
